services:
  postgres-db:
    image: postgis/postgis:latest
    container_name: postgres  
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./volumes/postgres/db:/var/lib/postgresql/data

  server:
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: no
    container_name: server
    depends_on:
      - postgres-db
    ports:
      - "1337:1337" 
    environment:
      - APP_ID=myAppId
      - MASTER_KEY=myMasterKey
      - SERVER_URL=http://localhost:1337/parse
      - DATABASE_URI=postgres://postgres:password@postgres-db:5432/postgres

  dashboard:
    image: parseplatform/parse-dashboard
    platform: linux/x86_64
    restart: unless-stopped
    container_name: dashboard
    ports:
      - "4040:4040"
    command: --dev --appId myAppId --masterKey myMasterKey --serverURL http://localhost:1337/parse
